/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adso39.vistas;

import com.adso39.controladores.ControlUsuarios;
import com.adso39.modelos.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dario
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());
    
    private ControlUsuarios elControlUsuarios;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        this.elControlUsuarios = new ControlUsuarios();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblEsAdministrador = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        cmbCargo = new javax.swing.JComboBox<>();
        chbEsAdministrador = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCapturarInformacion = new javax.swing.JButton();
        btnCapturarInformacion2 = new javax.swing.JButton();
        btnCapturarInformacion3 = new javax.swing.JButton();
        btnCapturarInformacion4 = new javax.swing.JButton();
        btnAgregarUsuario = new javax.swing.JButton();
        btnListarUsuario = new javax.swing.JButton();
        btnInformacionObjContrEstatic = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnMostrarUsuarios = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GESTION DE USUARIOS");

        lblIdentificacion.setText("Identificacion:");

        lblNombres.setText("Nombres:");

        lblApellidos.setText("Apellidos:");

        lblCargo.setText("Cargo:");

        lblEsAdministrador.setText("Es Administrador:");

        txtIdentificacion.setText("jTextField1");

        txtNombres.setText("jTextField2");
        txtNombres.addActionListener(this::txtNombresActionPerformed);

        txtApellidos.setText("jTextField3");
        txtApellidos.addActionListener(this::txtApellidosActionPerformed);

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprendiz", "Funcionario", "Visitante", "Instructor" }));

        chbEsAdministrador.setText("Si");
        chbEsAdministrador.addActionListener(this::chbEsAdministradorActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnCapturarInformacion.setText("Capturar Información");
        btnCapturarInformacion.addActionListener(this::btnCapturarInformacionActionPerformed);

        btnCapturarInformacion2.setText("Capturar Información Objeto");
        btnCapturarInformacion2.addActionListener(this::btnCapturarInformacion2ActionPerformed);

        btnCapturarInformacion3.setText("Capturar Información Obj-Constructor");
        btnCapturarInformacion3.addActionListener(this::btnCapturarInformacion3ActionPerformed);

        btnCapturarInformacion4.setText("Capturar Información Obj-Control");
        btnCapturarInformacion4.addActionListener(this::btnCapturarInformacion4ActionPerformed);

        btnAgregarUsuario.setText("Agregar Usuario");
        btnAgregarUsuario.addActionListener(this::btnAgregarUsuarioActionPerformed);

        btnListarUsuario.setText("Listado Usuario");
        btnListarUsuario.addActionListener(this::btnListarUsuarioActionPerformed);

        btnInformacionObjContrEstatic.setText("Capturar Informacion Obj-Control Estatico");
        btnInformacionObjContrEstatic.addActionListener(this::btnInformacionObjContrEstaticActionPerformed);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblUsuarios);

        btnMostrarUsuarios.setText("Mostrar Usuarios");
        btnMostrarUsuarios.addActionListener(this::btnMostrarUsuariosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEsAdministrador)
                        .addGap(18, 18, 18)
                        .addComponent(chbEsAdministrador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdentificacion)
                            .addComponent(lblNombres)
                            .addComponent(lblApellidos)
                            .addComponent(lblCargo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCapturarInformacion2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCapturarInformacion3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCapturarInformacion4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnInformacionObjContrEstatic)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCapturarInformacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarUsuarios)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCapturarInformacion))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdentificacion)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombres)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidos)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCargo)
                            .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnCapturarInformacion2)
                        .addGap(7, 7, 7)
                        .addComponent(btnCapturarInformacion3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapturarInformacion4)
                        .addGap(18, 18, 18)
                        .addComponent(btnInformacionObjContrEstatic)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEsAdministrador)
                            .addComponent(chbEsAdministrador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListarUsuario)
                            .addComponent(btnAgregarUsuario))
                        .addGap(24, 24, 24)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapturarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarInformacionActionPerformed
        // TODO add your handling code here:
        String identificacion = txtIdentificacion.getText();
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        int indiceCargo = cmbCargo.getSelectedIndex();
        String textoCargo = cmbCargo.getSelectedItem().toString();
        boolean esAdministrador = chbEsAdministrador.isSelected();
        
        String textoMostrar = "Identificación: " + identificacion + "\n" +
                "Nombre Completo: " + nombres + " " + apellidos + "\n" +
                "Cargo: (" + indiceCargo + ") " + textoCargo  + "\n";
        
        if (esAdministrador) {
            textoMostrar += "El usuario es administrador";
        }
        else {
            textoMostrar += "El usuario no es administrador";
        }
        
        jTextArea1.setText(textoMostrar);
    }//GEN-LAST:event_btnCapturarInformacionActionPerformed

    private void btnCapturarInformacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarInformacion2ActionPerformed
        // TODO add your handling code here:
        Usuario elUsuario = new Usuario();
        
        String identificacion = txtIdentificacion.getText();
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        int indiceCargo = cmbCargo.getSelectedIndex();
        String textoCargo = cmbCargo.getSelectedItem().toString();
        boolean esAdministrador = chbEsAdministrador.isSelected();
        
        elUsuario.setIdentificacion(identificacion);
        elUsuario.setNombres(nombres);
        elUsuario.setApellidos(apellidos);
        elUsuario.setIndiceCargo(indiceCargo);
        elUsuario.setTextoCargo(textoCargo);
        elUsuario.setEsAdministrador(esAdministrador);
        
        jTextArea1.setText(elUsuario.toString());
    }//GEN-LAST:event_btnCapturarInformacion2ActionPerformed

    private void btnCapturarInformacion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarInformacion3ActionPerformed
        // TODO add your handling code here:
        Usuario elUsuario = new Usuario(txtIdentificacion.getText(),
            txtNombres.getText(),
            txtApellidos.getText(),
            cmbCargo.getSelectedIndex(),
            cmbCargo.getSelectedItem().toString(),
            chbEsAdministrador.isSelected());
        
        jTextArea1.setText(elUsuario.toString());
    }//GEN-LAST:event_btnCapturarInformacion3ActionPerformed

    private void btnCapturarInformacion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarInformacion4ActionPerformed
        // TODO add your handling code here:
        this.elControlUsuarios.RegistrarUsuario(txtIdentificacion.getText(),
            txtNombres.getText(),
            txtApellidos.getText(),
            cmbCargo.getSelectedIndex(),
            cmbCargo.getSelectedItem().toString(),
            chbEsAdministrador.isSelected());
        
        jTextArea1.setText(this.elControlUsuarios.ImprimirUsuario());        
    }//GEN-LAST:event_btnCapturarInformacion4ActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        ControlUsuarios.AgregarUsuario(txtIdentificacion.getText(),
                txtNombres.getText(),
                txtApellidos.getText(),
                cmbCargo.getSelectedIndex(),
                cmbCargo.getSelectedItem().toString(),
                chbEsAdministrador.isSelected());
        
        jTextArea1.setText("Agregado:\n" +
                txtNombres.getText() +
                " " +
                txtApellidos.getText());
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuarioActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(ControlUsuarios.ListarUsuarios());
    }//GEN-LAST:event_btnListarUsuarioActionPerformed

    private void btnInformacionObjContrEstaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionObjContrEstaticActionPerformed
        // TODO add your handling code here:
       ControlUsuarios.AgregarUsuario(this.txtIdentificacion.getText(),
                this.txtNombres.getText(),
                this.txtApellidos.getText(),
                this.cmbCargo.getSelectedIndex(),
                this.cmbCargo.getSelectedItem().toString(),
                this.chbEsAdministrador.isSelected());
       
       jTextArea1.setText(ControlUsuarios.ImprimirUsuario());
    }//GEN-LAST:event_btnInformacionObjContrEstaticActionPerformed

    private void chbEsAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbEsAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbEsAdministradorActionPerformed

    private void btnMostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarUsuariosActionPerformed
        // TODO add your handling code here:
        ControlUsuarios.MostrarUsuarios();
        ArrayList<Usuario> losUsuarios = ControlUsuarios.MostrarUsuarios();
        /*
        "(identificacion, nombres, apellidos," +
                " indiceCargo, textoCargo, esAdministrador) "
        */
        DefaultTableModel modeloUsuarios = new DefaultTableModel();
        modeloUsuarios.addColumn("Identificacion");
        modeloUsuarios.addColumn("Nombre Completo");
        modeloUsuarios.addColumn("Cargo");
        modeloUsuarios.addColumn("Es Administrador");
        for (int index = 0;
                index<losUsuarios.size();
                index++) {
            Object[] fila = new Object[4];
            
            fila[0] = losUsuarios.get(index).getIdentificacion();
            fila[1] = losUsuarios.get(index).getNombres() + " " +
                    losUsuarios.get (index).getApellidos();
            fila[2] = losUsuarios.get(index).getTextoCargo();
            if (losUsuarios.get(index).isEsAdministrador()) {
                fila[3] = "Si";
            } else {
                fila [3] = "No";
            }
            
            modeloUsuarios.addRow(fila);
        }
        tblUsuarios.setModel(modeloUsuarios);
    }//GEN-LAST:event_btnMostrarUsuariosActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnCapturarInformacion;
    private javax.swing.JButton btnCapturarInformacion2;
    private javax.swing.JButton btnCapturarInformacion3;
    private javax.swing.JButton btnCapturarInformacion4;
    private javax.swing.JButton btnInformacionObjContrEstatic;
    private javax.swing.JButton btnListarUsuario;
    private javax.swing.JButton btnMostrarUsuarios;
    private javax.swing.JCheckBox chbEsAdministrador;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblEsAdministrador;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
